WikiHash/WikiHash/Controllers/ExploreController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WikiHash.Models.Articles;

namespace WikiHash.Controllers
{
    public class ExploreController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public string GetArticlesAJAX(string filter, string category)
        {
            var articles = ArticlesManager.GetFilteredArticles(filter, category);
            return JsonConvert.SerializeObject(articles);
        }

        [HttpGet]
        public ActionResult New()
        {
            if (!Models.Permissions.PermissionChecker.CheckPermission(User.Identity.Name, Models.Permissions.PermissionTarget.CreatingNewArticles))
                return RedirectToAction("Login", "Account", new { returnUrl = Url.Action("New") });

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New(ArticleCreationModel model)
        {
            try
            {
                if (!Models.Permissions.PermissionChecker.CheckPermission(User.Identity.Name, Models.Permissions.PermissionTarget.CreatingNewArticles))
                    return RedirectToAction("Login", "Account", new { returnUrl = Url.Action("New") });

                if (!ModelState.IsValid)
                    return View(model);

                var article = ArticlesManager.AddArticle(model);
                NewArticleGenerator.Create(article);
                return RedirectToAction("ArticleCreated");
            }
            catch(Models.EntryExistsException e)
            {
                return View("Error", null, "Article with this title already exists.");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult ArticleCreated()
        {
            return View("MessagePage", new Models.MessageViewModel { Title = "Article created", Message = "Article was created successfully." });
        }
    }
}

WikiHash/WikiHash/Controllers/MediasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WikiHash.Models.Medias;
using Newtonsoft.Json;

namespace WikiHash.Controllers
{
    public class MediasController : Controller
    {
        public ActionResult Show(string link)
        {
            try
            {
                if (!Models.Permissions.PermissionChecker.CheckPermission(User.Identity.Name, Models.Permissions.PermissionTarget.ReadingArticles))
                    return RedirectToAction("Login", "Account", new { returnUrl = Url.Action("Show") });

                var media = MediasManager.GetMedia(link);
                var viewMedia = MediaViewModel.FromMedia(media);
                return View(viewMedia);
            }
            catch(KeyNotFoundException e)
            {
                return View("Error", null, "No matching media found.");
            }
            catch
            {
                return View("Error");
            }
        }

        [HttpGet]
        public ActionResult New()
        {
            if (!Models.Permissions.PermissionChecker.CheckPermission(User.Identity.Name, Models.Permissions.PermissionTarget.CreatingNewMedias))
                return RedirectToAction("Login", "Account", new { returnUrl = Url.Action("New") });

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New(MediaCreationModel model)
        {
            try
            {
                if (!Models.Permissions.PermissionChecker.CheckPermission(User.Identity.Name, Models.Permissions.PermissionTarget.CreatingNewMedias))
                    return RedirectToAction("Login", "Account", new { returnUrl = Url.Action("New") });

                if (!ModelState.IsValid)
                    return View(model);

                MediasManager.AddMedia(model);
                var path = Models.PathsGenerator.Media(model.File.FileName);
                model.File.SaveAs(path);

                return RedirectToAction("MediasUploadingComplete");
            }
            catch(Models.EntryExistsException e)
            {
                return View("Error", null, "Media with the selected title already exists.");
            }
            catch
            {
                return View("Error");
            }
        }

        public ActionResult Explore()
        {
            return View();
        }

        public ActionResult MediasUploadingComplete()
        {
            return View("MessagePage", new WikiHash.Models.MessageViewModel { Title = "Media uploaded", Message = "Media has been uploaded successfully." });
        }

        public string GetMediaUrl(string link)
        {
            var media = MediasManager.GetMedia(link);
            var viewMedia = MediaViewModel.FromMedia(media);
            var json = JsonConvert.SerializeObject(viewMedia);
            return json;
        }

        public string GetMediasAJAX(string filter = "")
        {
            var list = MediasManager.GetFilteredMedias(filter);
            return JsonConvert.SerializeObject(list);
        }
    }
}

WikiHash/WikiHash/Views/Shared/MessagePage.cshtml
@model WikiHash.Models.MessageViewModel
@{
    ViewBag.Title = Model.Title;
}
<div class="article-body">
    <div class="container">
        <h1 class="underlined">@Model.Title</h1>
        <br />
        <p>@Model.Message</p>
    </div>
</div>

WikiHash/WikiHash/Views/Shared/_EditorDialogPartial.cshtml
<div id="edit-frame-dialog" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Content Frame</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <input id="edit-frame-id" type="hidden" />
                    Column width:
                    <select id="edit-width-input">
                        <option value="1">1/6</option>
                        <option value="2">2/6</option>
                        <option value="3">3/6</option>
                        <option value="4">4/6</option>
                        <option value="5">5/6</option>
                        <option value="6">6/6</option>
                        <option value="auto">auto</option>
                    </select>

                    <ul class="list-inline edit-topbar underlined">
                        <li selected class="list-inline-item" data-tab="edit-text-tab">Text</li>
                        <li class="list-inline-item" data-tab="edit-media-tab">Media</li>
                    </ul>
                    <div id="edit-tabs">
                        <!--Text editor-->
                        <div id="edit-text-tab" style="display: none;">
                            <div id="quill"></div>
                        </div>

                        <!--Media editor-->
                        <div id="edit-media-tab" style="display: none;">

                            <h4>Selected: <span id="selected-media-link"></span></h4>

                            <select id="media-size">
                                <option selected value="small">Small</option>
                                <option value="normal">Normal</option>
                                <option value="big">Big</option>
                            </select>

                            <div>
                                <input id="medias-filter-input" type="text" placeholder="filter" />
                                <button id="medias-filter-button-editor" type="button" class="btn btn-primary">
                                    <span class="fa fa-search" aria-hidden="true"></span>
                                </button>

                                <div id="medias-container"></div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button id="edit-save-button" type="button" class="btn btn-primary">Save changes</button>
                <button id="edit-remove-button" type="button" class="btn btn-danger">Remove frame</button>
            </div>
        </div>
    </div>
</div>

WikiHash/WikiHash/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Configuration.WebsiteName</title>
    @if (ViewBag.Tags != null)
    {
        <meta name="keywords" content="@ViewBag.Tags">
    }
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light noselect">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">@Configuration.WebsiteName</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Articles
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Index", "Explore")">Explorer</a>
                        <a class="dropdown-item" href="@Url.Action("New", "Explore")">Add</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Medias
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("Explore", "Medias")">Explorer</a>
                        <a class="dropdown-item" href="@Url.Action("New", "Medias")">Add</a>
                    </div>
                </li>
            </ul>
            <div class="text-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="nav-item dropdown login-panel">
                        <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-user-circle" aria-hidden="true"></span> @User.Identity.Name
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                            @if (User.IsInRole(WikiHash.Models.DefaultRolesNames.HeadAdmin))
                            {
                                <p>Head Admin</p>
                            }

                            <a class="dropdown-item" href="@Url.Action("Index", "Manage")"><span class="fa fa-user-circle" aria-hidden="true"></span> Account</a>

                            <div class="dropdown-divider"></div>
                            @using (Html.BeginForm("Logoff", "Account", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="dropdown-item"><span class="fa fa-sign-out" aria-hidden="true"></span> Logout</button>
                            }

                        </div>
                    </div>
                }
                else
                {
                    <a class="nav-link login-panel" href="@Url.Action("Login", "Account")"><span class="fa fa-user-circle" aria-hidden="true"></span> Login</a>
                }
            </div>
        </div>
    </nav>

    <main>
        @RenderBody()
    </main>

    <footer>
        <p>Powered by <a href="https://github.com/piter10p/WikiHash">WikiHash <span class="fa fa-github" aria-hidden="true"></span></a></p>
    </footer>

    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>